# Generated by Django 6.0.5 on 2026-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_code',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
