# Generated by Django 6.0.5 on 2026-06-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
